# Generated by Django 4.2.16 on 2024-10-09 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskTitle', models.CharField(default='tasktitle', max_length=50)),
                ('Description', models.TextField(blank=True, null=True)),
                ('DueDate', models.DateTimeField(db_column='duedate')),
                ('CompletedDate', models.DateTimeField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Improtant', models.BooleanField(default=False)),
                ('Status', models.CharField(default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
