# Generated by Django 4.2.16 on 2024-10-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Improtant',
            new_name='Important',
        ),
    ]
